# Generated by Django 4.1.3 on 2022-11-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Thương hiệu', 'verbose_name_plural': 'Thương hiệu'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Danh mục sản phẩm', 'verbose_name_plural': 'Danh mục sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_added',), 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Hình ảnh sản phẩm', 'verbose_name_plural': 'Hình ảnh sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Đánh giá'},
        ),
    ]
