# Generated by Django 4.1.3 on 2022-11-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, help_text='Kích thước tiêu chuẩn banner: 1920 x 520px', null=True, upload_to='uploads/banner'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='File PNG, kích thước: 64 x 64 px', null=True, upload_to='uploads/icons'),
        ),
    ]
