# Generated by Django 4.1.3 on 2022-11-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_brand_id_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Giá trị thuộc tính', 'verbose_name_plural': 'Giá trị thuộc tính'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Thuộc tính', 'verbose_name_plural': 'Thuộc tính'},
        ),
        migrations.AddField(
            model_name='category',
            name='visibleHomepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
