# Generated by Django 4.1.3 on 2022-12-04 04:27

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_brand_slug_alter_category_slug_alter_product_price_and_more'),
    ]

    operations = [
                UnaccentExtension()

    ]

