# Generated by Django 4.1.3 on 2022-12-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='footer_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='hotline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='map_iframe',
            field=models.TextField(blank=True, help_text='Thêm iframe map với kích thước width=100%, heigh=300', null=True),
        ),
    ]
