# Generated by Django 4.1.3 on 2022-11-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_alter_coupon_options_alter_promotion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='banner_size',
            field=models.CharField(blank=True, choices=[('banner', 'Banner trang chủ: 1920x520 px'), ('home1', 'Ảnh trang chủ nhỏ: 270x340 px'), ('home2', 'Ảnh trang chủ lớn: 565x340 px'), ('promotion', 'Ảnh ngang promotion: 1920x400 px')], default='banner', max_length=9, null=True),
        ),
    ]
