# Generated by Django 4.1.3 on 2022-11-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_alter_promotion_banner_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='link',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='banner_size',
            field=models.CharField(blank=True, choices=[('banner', 'Banner trang chủ: 1920x520 px'), ('home1', 'Ảnh trang chủ nhỏ 1: 270x340 px'), ('home3', 'Ảnh trang chủ nhỏ 2: 270x340 px'), ('home2', 'Ảnh trang chủ lớn giữa: 565x340 px'), ('promotion', 'Ảnh ngang promotion: 1920x400 px')], default='banner', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
