# Generated by Django 4.1.3 on 2022-12-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_alter_policy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ('sort',), 'verbose_name': 'Trang nội dung', 'verbose_name_plural': 'Trang nội dung'},
        ),
    ]
